define(["require", "exports"], function (require, exports) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    exports.TVKeyCodeConfig = void 0;
    var TVKeyCodeConfig = (function () {
        function TVKeyCodeConfig() {
        }
        TVKeyCodeConfig.NULL_KEY = "NULL_KEY";
        TVKeyCodeConfig.UP_KEY = "UP_KEY";
        TVKeyCodeConfig.LEFT_KEY = "LEFT_KEY";
        TVKeyCodeConfig.RIGHT_KEY = "RIGHT_KEY";
        TVKeyCodeConfig.DOWN_KEY = "DOWN_KEY";
        TVKeyCodeConfig.OK_KEY = "OK_KEY";
        TVKeyCodeConfig.GUIDE_KEY = "GUIDE_KEY";
        TVKeyCodeConfig.TT_KEY = "TT_KEY";
        TVKeyCodeConfig.POWER_KEY = "POWER_KEY";
        TVKeyCodeConfig.LIVE_KEY = "LIVE_KEY";
        TVKeyCodeConfig.MENU_KEY = "MENU_KEY";
        TVKeyCodeConfig.INFO_KEY = "INFO_KEY";
        TVKeyCodeConfig.EXIT_KEY = "EXIT_KEY";
        TVKeyCodeConfig.AUDIO_KEY = "AUDIO_KEY";
        TVKeyCodeConfig.MUTE_KEY = "MUTE_KEY";
        TVKeyCodeConfig.VOLUME_UP_KEY = "VOLUME_UP_KEY";
        TVKeyCodeConfig.VOLUME_DOWN_KEY = "VOLUME_DOWN_KEY";
        TVKeyCodeConfig.PAUSEPLAY_KEY = "PAUSEPLAY_KEY";
        TVKeyCodeConfig.RED_KEY = "RED_KEY";
        TVKeyCodeConfig.GREEN_KEY = "GREEN_KEY";
        TVKeyCodeConfig.YELLOW_KEY = "YELLOW_KEY";
        TVKeyCodeConfig.BLUE_KEY = "BLUE_KEY";
        TVKeyCodeConfig.WHITE_KEY = "WHITE_KEY";
        TVKeyCodeConfig.BACK_KEY = "BACK_KEY";
        TVKeyCodeConfig.OPTION_KEY = "OPTION_KEY";
        TVKeyCodeConfig.FBWD_KEY = "FBWD_KEY";
        TVKeyCodeConfig.FFWD_KEY = "FFWD_KEY";
        TVKeyCodeConfig.SKIP_FFWD_KEY = "SKIP_FFWD_KEY";
        TVKeyCodeConfig.SKIP_FBWD_KEY = "SKIP_FBWD_KEY";
        TVKeyCodeConfig.SEARCH_KEY = "SEARCH_KEY";
        TVKeyCodeConfig.RECORD_KEY = "RECORD_KEY";
        TVKeyCodeConfig.CHANNEL_UP_KEY = "CHANNEL_UP_KEY";
        TVKeyCodeConfig.CHANNEL_DOWN_KEY = "CHANNEL_DOWN_KEY";
        TVKeyCodeConfig.ZERO_KEY = "ZERO_KEY";
        TVKeyCodeConfig.ONE_KEY = "ONE_KEY";
        TVKeyCodeConfig.TWO_KEY = "TWO_KEY";
        TVKeyCodeConfig.THREE_KEY = "THREE_KEY";
        TVKeyCodeConfig.FOUR_KEY = "FOUR_KEY";
        TVKeyCodeConfig.FIVE_KEY = "FIVE_KEY";
        TVKeyCodeConfig.SIX_KEY = "SIX_KEY";
        TVKeyCodeConfig.SEVEN_KEY = "SEVEN_KEY";
        TVKeyCodeConfig.EIGHT_KEY = "EIGHT_KEY";
        TVKeyCodeConfig.NINE_KEY = "NINE_KEY";
        TVKeyCodeConfig.DELETE_KEY = "DELETE_KEY";
        TVKeyCodeConfig.MAGENTA_KEY = "MAGENTA_KEY";
        TVKeyCodeConfig.VOICE_KEY = "VOICE_KEY";
        TVKeyCodeConfig.AUTOCLOSE_1_KEY = "AUTOCLOSE_1_KEY";
        TVKeyCodeConfig.AUTOCLOSE_2_KEY = "AUTOCLOSE_2_KEY";
        TVKeyCodeConfig.CUSTOM1_KEY = "CUSTOM1_KEY";
        TVKeyCodeConfig.CUSTOM2_KEY = "CUSTOM2_KEY";
        TVKeyCodeConfig.KEYEVENT_UP_KEY = "KEYEVENT_UP_KEY";
        TVKeyCodeConfig.POWER_ON = "POWER_ON";
        TVKeyCodeConfig.POWER_OFF = "POWER_OFF";
        TVKeyCodeConfig.FAVOURITES_KEY = "FAVOURITES_KEY";
        TVKeyCodeConfig.SHORTCUT1_KEY = "SHORTCUT1_KEY";
        TVKeyCodeConfig.SHORTCUT2_KEY = "SHORTCUT2_KEY";
        TVKeyCodeConfig.SHORTCUT3_KEY = "SHORTCUT3_KEY";
        TVKeyCodeConfig.SHORTCUT4_KEY = "SHORTCUT4_KEY";
        TVKeyCodeConfig.SHORTCUT5_KEY = "SHORTCUT5_KEY";
        TVKeyCodeConfig.SHORTCUT6_KEY = "SHORTCUT6_KEY";
        TVKeyCodeConfig.SHORTCUT7_KEY = "SHORTCUT7_KEY";
        TVKeyCodeConfig.SHORTCUT8_KEY = "SHORTCUT8_KEY";
        TVKeyCodeConfig.SHORTCUT9_KEY = "SHORTCUT9_KEY";
        TVKeyCodeConfig.COMPANION_KEY = "COMPANION_KEY";
        TVKeyCodeConfig.UNSILENT_KEY = "UNSILENT_KEY";
        TVKeyCodeConfig.SILENT_KEY = "SILENT_KEY";
        TVKeyCodeConfig.PLAY_KEY = "PLAY_KEY";
        TVKeyCodeConfig.PAUSE_KEY = "PAUSE_KEY";
        TVKeyCodeConfig.FBWD_NORMALSPEED_KEY = "FBWD_NORMALSPEED_KEY";
        TVKeyCodeConfig.FFWD_NORMALSPEED_KEY = "FFWD_NORMALSPEED_KEY";
        TVKeyCodeConfig.FBWD_FASTSPEED_KEY = "FBWD_FASTSPEED_KEY";
        TVKeyCodeConfig.FFWD_FASTSPEED_KEY = "FFWD_FASTSPEED_KEY";
        TVKeyCodeConfig.MYRECORDING_KEY = "MYRECORDING_KEY";
        TVKeyCodeConfig.RECORD_ONLY_KEY = "RECORD_ONLY_KEY";
        return TVKeyCodeConfig;
    }());
    exports.TVKeyCodeConfig = TVKeyCodeConfig;
});
//# sourceMappingURL=keycode.config.js.map